version: '3'

services:
  postgres:
    image: 'postgres'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: security
      POSTGRES_PASSWORD: security@00
      POSTGRES_DB: security-db

volumes:
  pgdata: